spring:
  data:
    mongodb:
      uri: mongodb+srv://shauryad110:nItQoVbZE39BAkeY@cluster0.xshb7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

  main:
    allow-circular-references: true

server:
  port: 8080
  servlet:
    context-path: /journal

